name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        cat src/App.js;
        docker build . --file Dockerfile --tag portfolio:latest; 
        echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin;
        docker tag portfolio $DOCKER_HUB_USERNAME/portfolio:latest;
        docker push $DOCKER_HUB_USERNAME/portfolio:latest
        
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: davidkopala.com
        username: ubuntu
        key: ${{ secrets.SERVER_KEY }}
        script: |
          docker pull davidkopala/portfolio
          docker restart portfolio
        
        
